### PR TITLE
Run tests for python-3.7 in travis

### PR DESCRIPTION
**Pull request by gonzalobf**
I just realized that the library supports python3.7 but it is not tested with this version in travis

### CODE REVIEW

**Comment by gonzalobf** [comment]
Flake8 is failing for code that is already commit in master. I can fix it here or wait until #68 is merged. I would be happy to wait and rebase my branch once  #68 is merge but I don't if it will be merged soon. 

Thank you

**Comment by qsoftdevelopment** [comment]
@gonzalobf Can you wait a couple of days as we are releasing a new version? It will have conflicts with your current code. 
Python 3.7 is supported and we will resolve possible issues with it.

**Comment by gonzalobf** [comment]
@qsoftdevelopment yes sure, thank you.

**Comment by qsoftdevelopment** [comment]
@gonzalobf Can you try now with the latest Python SDK?

**Comment by qsoftdevelopment** [comment]
@gonzalobf We have detected the problem. It's the issue with the outdated library. This is not a quick fix and we should have the fix in the next Python SDK release.

**Comment by gonzalobf** [comment]
@qsoftdevelopment I rebased my branch to v4.1.4 branch and run tests locally. Asyncio tests still failing, so I'm not totally sure if it is fixed in that version.

**Comment by qsoftdevelopment** [comment]
Hi @gonzalobf ,

V4.1.1 is pending release. In the meantime, you can check `develop` branch (https://github.com/pubnub/python/tree/develop) as it will be in v4.1.4. It should fix your problem. Let me know if it does not.

**Pull request closed without merging**
